# command it with `podman-compose up -d` then `podman exec maven -it /bin/sh`
services:
  pg:
    container_name: postgres
    image: postgres:16.9-alpine3.22
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
        - private_network

  mvn:
    container_name: maven
    build: .
    depends_on:
      - pg
    volumes:
      - .:/app
    working_dir: /app
    # command: /bin/sh -c "tail -f /dev/null"
    command: 
      - /bin/sh
      - -c
      - |
        trap 'echo "Received SIGTERM, exiting gracefully"; exit 0' SIGTERM
        tail -f /dev/null & wait $!
    networks:
      - private_network

networks:
  private_network:
    driver: bridge
